site_name: Matheus Fabião Portfólio
site_description: Site pessoal do Matheus Fabião, desenvolvedor de software.
site_author: Matheus Fabião
repo_url: https://github.com/matheusfabiao/matheusfabiao_portfolio_website
repo_name: 'Matheus Fabião Portfólio'
edit_uri: tree/main/docs

theme:
  name: material
  language: pt-BR
  logo: assets/Logo Verde.png
  favicon: assets/Logo Verde.png

nav:
  - Início: index.md
  - Começando:
    - Instalação: getting-started/installation.md
    - Configuração: getting-started/configuration.md

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css